title: Twannes Claes | Portfolio
author: Twannes Claes
description: Check out my portfolio!

collections:
  projects:
    output: true
    permalink: /projects/:name.html

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
